name: calculator_app_testing
description: Calculator app for testing purpose.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  calculator:
    path: packages/calculator
  flutter:
    sdk: flutter
  material_segmented_control: ^3.1.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true

